name: Style-Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  style_check:
    name: Style-Check
    runs-on: ubuntu-22.04
    steps:
      - name: Install clang-format
        run: |
          wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository --yes "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"
          sudo apt-get install -y clang-format-16
      - uses: actions/checkout@v3
      - name: Run format check
        run: .ci/check_format.sh
      - name: Save PR number
        if: ${{ failure() && github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          name: pr
          path: pr/
  plugin_check:
    name: Plugin-Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run plugin check
        run: .ci/check_plugins.sh
